name: localized_rich_text
description: A flutter plugin to facilitate the localization of a RichText
version: 0.0.6
homepage: https://github.com/LaTrita97/localized_rich_text

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.localized_rich_text
        pluginClass: LocalizedRichTextPlugin
      ios:
        pluginClass: LocalizedRichTextPlugin
      # macos:
      #   pluginClass: HelloPlugin
      web:
        pluginClass: LocalizedRichTextWeb
        fileName: localized_rich_text_web.dart
